spring:
  datasource:
    url: jdbc:h2:mem:productsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: myuser
    password: secret
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console